<form id="edit_form" action="<?php echo APP_URL . '/match/save/' ?>" method="post">
	<fieldset>
		<legend>Match info</legend>
		<ul>
			<li class="left">
				<label for="season">Season:</label>
				<input type="text" name="season" id="season" />
			</li>
			<li class="right">
				<label for="datetime">Date/Time:</label>
				<input type="text" name="datetime" id="datetime" />
			</li>
			<li class="left">
				<label for="code">Code:</label>
				<input type="text" name="code" id="code" />
			</li>
			<li class="right">
				<label for="grade">Grade:</label>
				<input type="text" name="grade" id="grade" />
			</li>
			<li class="left">
				<label for="type">Type:</label>
				<input type="text" name="type" id="type" />
			</li>
			<li class="right">
				<label for="competition">Competition:</label>
				<input type="text" name="competition" id="competition" />
			</li>
			<li class="left">
				<label for="team1">Team:</label>
				<input type="text" name="team1" id="team1" />
			</li>
			<li class="right">
				<label for="score1">Score:</label>
				<input type="text" name="score1" id="score1" />
			</li>
			<li class="left">
				<label for="team2">Team:</label>
				<input type="text" name="team2" id="team2" />
			</li>
			<li class="right">
				<label for="score2">Score:</label>
				<input type="text" name="score2" id="score2" />
			</li>
			<li class="left">
				<label for="venue">Venue:</label>
				<input type="text" name="venue" id="venue" />
			</li>
			<li class="right">
				<label for="address">Address:</label>
				<input type="text" name="address" id="address" />
			</li>
			<li class="left">
				<label for="referee_firstname">Ref Name:</label>
				<input type="text" name="referee_firstname" id="referee_firstname" />
			</li>
            <li class="right">
                <label for="referee_lastname">Surname:</label>
                <input type="text" name="referee_lastname" id="referee_lastname" />
            </li>
			<li class="left">
				<label for="referee_county">County:</label>
				<input type="text" name="referee_county" id="referee_county" />
			</li>
			<li class="right">
				<label for="referee_club">Club:</label>
				<input type="text" name="referee_club" id="referee_club" />
			</li>
            <li class="right">
                <label for="stage">Stage:</label>
                <input type="text" name="stage" id="stage" />
            </li>
			<li class="left">
				<input type="submit" name="save" value="Save" />
			</li>
		</ul>
	</fieldset>
</form>