<form id="edit_form">
	<fieldset>
		<legend>Match info</legend>
		<ul>
			<li class="left">
				<label for="season">Season:</label>
				<input type="text" name="season" id="season" />
			</li>
			<li class="right">
				<label for="datetime">Date/Time:</label>
				<input type="text" name="datetime" id="datetime" />
			</li>
			<li class="left">
				<label for="code">Code:</label>
				<input type="text" name="code" id="code" />
			</li>
			<li class="right">
				<label for="grade">Grade:</label>
				<input type="text" name="grade" id="grade" />
			</li>
			<li class="left">
				<label for="type">Type:</label>
				<input type="text" name="type" id="type" />
			</li>
			<li class="right">
				<label for="competition">Competition:</label>
				<input type="text" name="competition" id="competition" />
			</li>
			<li class="left">
				<label for="team1">Team:</label>
				<input type="text" name="team1" id="team1" />
			</li>
			<li class="right">
				<label for="score1">Score:</label>
				<input type="text" name="score1" id="score1" />
			</li>
			<li class="left">
				<label for="team2">Team:</label>
				<input type="text" name="team2" id="team2" />
			</li>
			<li class="right">
				<label for="score2">Score:</label>
				<input type="text" name="score2" id="score2" />
			</li>
			<li class="left">
				<label for="venue">Venue:</label>
				<input type="text" name="season" id="venue" />
			</li>
			<li class="right">
				<label for="address">Address:</label>
				<input type="text" name="address" id="address" />
			</li>
			<li class="left">
				<label for="referee">Referee:</label>
				<input type="text" name="referee" id="referee" />
			</li>
			<li class="right">
				<label for="county">County:</label>
				<input type="text" name="county" id="county" />
			</li>
			<li class="right">
				<label for="club">Club:</label>
				<input type="text" name="club" id="club" />
			</li>
			<li class="left">
				<input type="submit" name="save" value="Save" />
			</li>
		</ul>
	</fieldset>
</form>